{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<p>
{' <a href="%ezpublish_link">eZ Publish</a> Copyright &copy; 1999-2024 <a href="%netgen_link">Netgen</a> and others.'|i18n( 'design/admin/page_copyright',, hash( '%evaluate_link', 'https://netgen.io', '%share_link', 'https://share.se7enx.com', '%ezpublish_link', 'https://github.com/netgen/ezpublish-legacy', '%netgen_link', 'https://netgen.io' ) )}{' For more information see <a href=%about_link>ezinfo/about</a>.'|i18n( 'design/admin/page_copyright',, hash( '%edition', fetch( 'setup', 'edition' ), '%about_link', "/ezinfo/about"|ezurl ) )}
</p>
