{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<p>
{' <a href="%ezpublish_link">eZ Publish</a> Copyright &copy; 1999-2024 <a href="%7x_link">7x</a> and others.'|i18n( 'design/admin/page_copyright',, hash( '%evaluate_link', 'https://se7enx.com', '%share_link', 'https://share.se7enx.com', '%ezpublish_link', 'https://ezpublishlegacy.se7enx.com', '%7x_link', 'https://se7enx.com' ) )}{' For more information see <a href=%about_link>ezinfo/about</a>.'|i18n( 'design/admin/page_copyright',, hash( '%edition', fetch( 'setup', 'edition' ), '%about_link', "/ezinfo/about"|ezurl ) )}
</p>