{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{"Tip: Store this page as an html file by clicking Save-As in your web browser menu, alternatively you may write down the URLs for your sites."|i18n('design/standard/setup/init')}
<p></p>
{"Make sure to visit the %1 and the %2 web site."|i18n("design/standard/setup/init",,array(concat( '<a href="https://share.se7enx.com/forums" target="_blank">', "forums"|i18n("design/standard/setup/init", 'forum link'), '</a>' ), concat(  '<a href="https://se7enx.com/about/technologies/what_is_ez_publish" target="_blank">', "eZ Publish"|i18n("design/standard/setup/init", 'eZ Publish link'), '</a>') ) ) }
