{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{"Discover the eZ Publish Platform forums"|i18n("design/standard/setup/init")}
<ul>
  <li><a href="https://share.se7enx.com/forums/ez-publish-platform" target="_blank">{"eZ Publish Platform"|i18n("design/standard/setup/init")}</a></li>
  <li><a href="https://share.se7enx.com/forums/install-configuration" target="_blank">{"Installation & configuration"|i18n("design/standard/setup/init")}</a></li>
  <li><a href="https://share.se7enx.com/forums/setup-design" target="_blank">{"Setup and design"|i18n("design/standard/setup/init")}</a></li>
  <li><a href="https://share.se7enx.com/forums/general" target="_blank">{"General"|i18n("design/standard/setup/init")}</a></li>
</ul>
