{* DO NOT EDIT THIS FILE! Use an override template instead. *}

<div align="center">
  <h1>{"Open source software is nothing without a vibrant community!"|i18n("design/standard/setup/init")}</h1>
</div>

{'<p>If you need to share knowledge, exchange tips with developers or simply find some improvement tricks, the eZ Community is the place to go.</p>
<p>How do you access it?</p>
<ul>
  <li>Go on %share_link%share.se7enx.com%a%</li>
  <li>Click on Register (top of the page) and create your profile</li>
  <li>Here you can check out the %blogs_link%blog posts%a%, %articles_link%articles%a%, %forums_link%forums%a% ...</li>
</ul></p>
<p>We’re looking forward to seeing what you share with the Community!</p>'|i18n('design/standard/setup/init',
    null,
    hash(
        '%a%', '</a>',
        '%share_link%', '<a href="https://share.se7enx.com/?utm_source=Setup%20Wizard&utm_medium=Setup%20Wizard&utm_campaign=Setup%20Wizard">',
        '%blogs_link%', '<a href="https://share.se7enx.com/blogs/?utm_source=Setup%20Wizard&utm_medium=Setup%20Wizard&utm_campaign=Setup%20Wizard">',
        '%articles_link%', '<a href="https://share.se7enx.com/learn/?utm_source=Setup%20Wizard&utm_medium=Setup%20Wizard&utm_campaign=Setup%20Wizard">',
        '%forums_link%', '<a href="https://share.se7enx.com/forums/?utm_source=Setup%20Wizard&utm_medium=Setup%20Wizard&utm_campaign=Setup%20Wizard">'
    )
)}

<form method="post" action="{$script}">
    <div class="buttonblock" align="right">
        {include uri='design:setup/init/navigation.tpl'}
    </div>
    {include uri='design:setup/persistence.tpl'}
</form>
