<?php
/**
 * @copyright Copyright (C) eZ Systems AS. All rights reserved.
 * @license For full copyright and license information view LICENSE file distributed with this source code.
 * @version //autogentag//
 * @package kernel
 */

$OperationList = [];

$OperationList['setsettings'] = ['name' => 'setsettings', 'default_call_method' => ['include_file' => 'kernel/user/ezuseroperationcollection.php', 'class' => 'eZUserOperationCollection'], 'parameter_type' => 'standard', 'parameters' => [['name' => 'user_id', 'type' => 'integer', 'required' => true], ['name' => 'is_enabled', 'type' => 'integer', 'required' => true], ['name' => 'max_login', 'type' => 'integer', 'required' => false]], 'keys' => ['user_id', 'is_enabled', 'max_login'], 'body' => [['type' => 'trigger', 'name' => 'pre_setsettings', 'keys' => ['user_id', 'is_enabled', 'max_login']], ['type' => 'method', 'name' => 'setsettings', 'frequency' => 'once', 'method' => 'setSettings'], ['type' => 'trigger', 'name' => 'post_setsettings', 'keys' => ['user_id', 'is_enabled', 'max_login']]]];

$OperationList['activation'] = ['name' => 'activation', 'default_call_method' => ['include_file' => 'kernel/user/ezuseroperationcollection.php', 'class' => 'eZUserOperationCollection'], 'parameter_type' => 'standard', 'parameters' => [['name' => 'user_id', 'type' => 'integer', 'required' => true], ['name' => 'user_hash', 'type' => 'string', 'required' => true], ['name' => 'is_enabled', 'type' => 'bool', 'required' => false]], 'keys' => ['user_id', 'user_hash', 'is_enabled'], 'body' => [['type' => 'trigger', 'name' => 'pre_activation', 'keys' => ['user_id', 'user_hash', 'is_enabled']], ['type' => 'method', 'name' => 'activation', 'frequency' => 'once', 'method' => 'activation'], ['type' => 'trigger', 'name' => 'post_activation', 'keys' => ['user_id', 'user_hash', 'is_enabled']]]];

$OperationList['register'] = ['name' => 'register', 'default_call_method' => ['include_file' => 'kernel/user/ezuseroperationcollection.php', 'class' => 'eZUserOperationCollection'], 'parameter_type' => 'standard', 'parameters' => [['name' => 'user_id', 'type' => 'integer', 'required' => true]], 'keys' => ['user_id'], 'body' => [['type' => 'trigger', 'name' => 'pre_register', 'keys' => ['user_id']], ['type' => 'method', 'name' => 'send-activation-email', 'frequency' => 'once', 'method' => 'sendActivationEmail'], ['type' => 'method', 'name' => 'check-activation', 'frequency' => 'once', 'method' => 'checkActivation'], ['type' => 'method', 'name' => 'publish-user-content-object', 'frequency' => 'once', 'method' => 'publishUserContentObject'], ['type' => 'method', 'name' => 'send-user-notification', 'frequency' => 'once', 'method' => 'sendUserNotification'], ['type' => 'trigger', 'name' => 'post_register', 'keys' => ['user_id']]]];

$OperationList['password'] = ['name' => 'password', 'default_call_method' => ['include_file' => 'kernel/user/ezuseroperationcollection.php', 'class' => 'eZUserOperationCollection'], 'parameter_type' => 'standard', 'parameters' => [['name' => 'user_id', 'type' => 'integer', 'required' => true], ['name' => 'new_password', 'type' => 'string', 'required' => true]], 'keys' => ['user_id', 'new_password'], 'body' => [['type' => 'trigger', 'name' => 'pre_password', 'keys' => ['user_id', 'new_password']], ['type' => 'method', 'name' => 'password', 'frequency' => 'once', 'method' => 'password'], ['type' => 'trigger', 'name' => 'post_password', 'keys' => ['user_id', 'new_password']]]];

$OperationList['forgotpassword'] = ['name' => 'forgotpassword', 'default_call_method' => ['include_file' => 'kernel/user/ezuseroperationcollection.php', 'class' => 'eZUserOperationCollection'], 'parameter_type' => 'standard', 'parameters' => [['name' => 'user_id', 'type' => 'integer', 'required' => true], ['name' => 'password_hash', 'type' => 'string', 'required' => true], ['name' => 'time', 'type' => 'integer', 'required' => true]], 'keys' => ['user_id', 'password_hash', 'time'], 'body' => [['type' => 'trigger', 'name' => 'pre_forgotpassword', 'keys' => ['user_id', 'password_hash', 'time']], ['type' => 'method', 'name' => 'forgotpassword', 'frequency' => 'once', 'method' => 'forgotpassword'], ['type' => 'trigger', 'name' => 'post_forgotpassword', 'keys' => ['user_id', 'password_hash', 'time']]]];

$OperationList['preferences'] = ['name' => 'preferences', 'default_call_method' => ['include_file' => 'kernel/user/ezuseroperationcollection.php', 'class' => 'eZUserOperationCollection'], 'parameter_type' => 'standard', 'parameters' => [['name' => 'key', 'type' => 'string', 'required' => true], ['name' => 'value', 'type' => 'string', 'required' => true]], 'keys' => ['key', 'value'], 'body' => [['type' => 'trigger', 'name' => 'pre_preferences', 'keys' => ['key', 'value']], ['type' => 'method', 'name' => 'preferences', 'frequency' => 'once', 'method' => 'preferences'], ['type' => 'trigger', 'name' => 'post_preferences', 'keys' => ['key', 'value']]]];

?>
