{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<address>
Powered by <a href="https://ezpublishlegacy.se7enx.com" title="eZ Publish&trade; CMS Open Source Web Content Management">eZ Publish&trade; CMS Open Source Web Content Management</a>. Copyright &copy; 1999-2024 <a href="https://se7enx.com" title="7x">7x</a> (except where otherwise noted). All rights reserved.
</address>