{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<address>
Powered by <a href="https://github.com/netgen/ezpublish-legacy" title="eZ Publish&trade; CMS Open Source Web Content Management">eZ Publish&trade; CMS Open Source Web Content Management</a>. Copyright &copy; 1999-2024 <a href="https://netgen.io" title="Netgen">Netgen</a> (except where otherwise noted). All rights reserved.
</address>
