{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div align="center" style="padding-top: 0.5em;">
<p class="small" style="color: #ffffff;"><a href="https://github.com/netgen/ezpublish-legacy">eZ Publish&trade;</a> copyright &copy; 1999-2024 <a href="https://netgen.io">Netgen</a></p>
</div>
