<?php
/**
 * @copyright Copyright (C) eZ Systems AS. All rights reserved.
 * @license For full copyright and license information view LICENSE file distributed with this source code.
 * @version //autogentag//
 * @package kernel
 */

$FunctionList = [];
$FunctionList['participant'] = ['name' => 'participant', 'operation_types' => ['read'], 'call_method' => ['class' => 'eZCollaborationFunctionCollection', 'method' => 'fetchParticipant'], 'parameter_type' => 'standard', 'parameters' => [['name' => 'item_id', 'required' => true, 'default' => false], ['name' => 'participant_id', 'required' => false, 'default' => false]]];
$FunctionList['participant_list'] = ['name' => 'participant_list', 'operation_types' => ['read'], 'call_method' => ['class' => 'eZCollaborationFunctionCollection', 'method' => 'fetchParticipantList'], 'parameter_type' => 'standard', 'parameters' => [['name' => 'item_id', 'required' => false, 'default' => false], ['name' => 'sort_by', 'required' => false, 'default' => false], ['name' => 'offset', 'required' => false, 'default' => false], ['name' => 'limit', 'required' => false, 'default' => false]]];
$FunctionList['participant_map'] = ['name' => 'participant_map', 'operation_types' => ['read'], 'call_method' => ['class' => 'eZCollaborationFunctionCollection', 'method' => 'fetchParticipantMap'], 'parameter_type' => 'standard', 'parameters' => [['name' => 'item_id', 'required' => false, 'default' => false], ['name' => 'sort_by', 'required' => false, 'default' => false], ['name' => 'offset', 'required' => false, 'default' => false], ['name' => 'limit', 'required' => false, 'default' => false], ['name' => 'field', 'required' => false, 'default' => false]]];
$FunctionList['message_list'] = ['name' => 'message_list', 'operation_types' => ['read'], 'call_method' => ['class' => 'eZCollaborationFunctionCollection', 'method' => 'fetchMessageList'], 'parameter_type' => 'standard', 'parameters' => [['name' => 'item_id', 'required' => true, 'default' => false], ['name' => 'sort_by', 'required' => false, 'default' => false], ['name' => 'offset', 'required' => false, 'default' => false], ['name' => 'limit', 'required' => false, 'default' => false]]];
$FunctionList['item_list'] = ['name' => 'item_list', 'operation_types' => ['read'], 'call_method' => ['class' => 'eZCollaborationFunctionCollection', 'method' => 'fetchItemList'], 'parameter_type' => 'standard', 'parameters' => [['name' => 'sort_by', 'required' => false, 'default' => false], ['name' => 'offset', 'required' => false, 'default' => false], ['name' => 'limit', 'required' => false, 'default' => false], ['name' => 'status', 'required' => false, 'default' => false], ['name' => 'is_read', 'required' => false, 'default' => null], ['name' => 'is_active', 'required' => false, 'default' => null], ['name' => 'parent_group_id', 'required' => false, 'default' => null]]];
$FunctionList['item_count'] = ['name' => 'item_count', 'operation_types' => ['read'], 'call_method' => ['class' => 'eZCollaborationFunctionCollection', 'method' => 'fetchItemCount'], 'parameter_type' => 'standard', 'parameters' => [['name' => 'is_read', 'required' => false, 'default' => null], ['name' => 'is_active', 'required' => false, 'default' => null], ['name' => 'parent_group_id', 'required' => false, 'default' => null], ['name' => 'status', 'required' => false, 'default' => false]]];
$FunctionList['group_tree'] = ['name' => 'group_tree', 'operation_types' => ['read'], 'call_method' => ['class' => 'eZCollaborationFunctionCollection', 'method' => 'fetchGroupTree'], 'parameter_type' => 'standard', 'parameters' => [['name' => 'parent_group_id', 'required' => true], ['name' => 'sort_by', 'required' => false, 'default' => false], ['name' => 'offset', 'required' => false, 'default' => false], ['name' => 'limit', 'required' => false, 'default' => false], ['name' => 'depth', 'required' => false, 'default' => false]]];

$FunctionList['tree_count'] = ['name' => 'tree_count', 'operation_types' => ['read'], 'call_method' => ['class' => 'eZContentFunctionCollection', 'method' => 'fetchObjectTreeCount'], 'parameter_type' => 'standard', 'parameters' => [['name' => 'parent_node_id', 'required' => true], ['name' => 'class_filter_type', 'required' => false, 'default' => false], ['name' => 'class_filter_array', 'required' => false, 'default' => false], ['name' => 'depth', 'required' => false, 'default' => 0]]];

?>
